### ISSUE TITLE
Switching tools in Firefox adds to controls rather than replacing

### ISSUE THREAD

**Issue by SpongeJr** [SpongeJr/CommunityPaint#3]
In Firefox, when you change tools, it starts adding the tool control elements to the HTML instead of replacing them. 

Suspect bad practices somewhere (or multiple places). Probably dealing with arrays and objects and that whole mess I made. Might be time to deal with that sooner rather than later.

**Comment by MrMagma** [comment]
innerText does not work on Firefox.
https://github.com/SpongeJr/CommunityPaint/blob/master/cpaint.html#L617
It was a quirky IE thing (all evil things have something to do with IE) and later adopted by the other browsers... Except for Firefox.
http://perfectionkills.com/the-poor-misunderstood-innerText/

**Comment by codeHusky** [comment]
innerHTML works better, anyway.

**Comment by SpongeJr** [comment]
Thanks! Got this fixed up and will be updating the main branch soon!
Went with textContent.

**Comment by SpongeJr** [comment]
Fixed in v0.75. Thanks for the help!
